version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

jobs:
  checkout-and-build:
    executor: maven-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven
      - run:
          name: Build with Maven
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target
          destination: builds

workflows:
  version: 2
  build:
    jobs:
      - checkout-and-build
